from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import matplotlib
import numpy as np
from PIL import Image, ImageDraw
from matplotlib.backends.backend_agg import FigureCanvasAgg
from matplotlib.colors import LightSource
from matplotlib.figure import Figure

from .config import PROFILES
from .model import BakedIsland

matplotlib.use("Agg")


def _write_json(path: Path, value: Any) -> None:
    path.write_text(json.dumps(value, ensure_ascii=False, indent=2), encoding="utf-8")


def _biome_rgb(island: BakedIsland) -> np.ndarray:
    rgb = np.full((*island.biome_ids.shape, 3), (83, 132, 145), dtype=np.uint8)
    for band_id, name in enumerate(island.config.band_names):
        rgb[island.biome_ids == band_id] = PROFILES[name].palette
    return rgb


def _material_rgb(island: BakedIsland, biome_rgb: np.ndarray) -> np.ndarray:
    materials = biome_rgb.copy()
    caldera = island.biome_ids == 3
    if np.any(caldera):
        lava_level = float(np.quantile(island.height[caldera], 0.52))
        materials[caldera & (island.height <= lava_level)] = (218, 75, 35)
    kiln = island.biome_ids == 4
    if np.any(kiln):
        hot_slope = float(np.quantile(island.slope[kiln], 0.88))
        materials[kiln & (island.slope >= hot_slope)] = (174, 66, 35)
    return materials


def _normal_rgb(island: BakedIsland) -> np.ndarray:
    spacing = island.config.world_size / (island.config.resolution - 1)
    dz, dx = np.gradient(island.height * island.config.world_height, spacing, spacing)
    nx = -dx
    ny = np.ones_like(dx)
    nz = -dz
    length = np.sqrt(nx * nx + ny * ny + nz * nz)
    normal = np.stack((nx / length, ny / length, nz / length), axis=-1)
    return np.clip((normal * 0.5 + 0.5) * 255.0, 0, 255).astype(np.uint8)


def _export_obj(path: Path, island: BakedIsland) -> None:
    target = min(island.config.obj_resolution, island.config.resolution)
    indices = np.linspace(0, island.config.resolution - 1, target).round().astype(int)
    sampled = island.height[np.ix_(indices, indices)]
    half = island.config.world_size / 2.0
    axis = np.linspace(-half, half, target)
    lines = ["# Generated by vertical-island-baker", "o VerticalIsland"]
    for row, z in enumerate(axis):
        for col, x in enumerate(axis):
            y = sampled[row, col] * island.config.world_height
            lines.append(f"v {x:.6f} {y:.6f} {z:.6f}")
    for row in range(target - 1):
        for col in range(target - 1):
            a = row * target + col + 1
            b = a + 1
            c = a + target
            d = c + 1
            lines.append(f"f {a} {c} {b}")
            lines.append(f"f {b} {c} {d}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _export_preview(path: Path, island: BakedIsland, biome_rgb: np.ndarray) -> None:
    light = LightSource(azdeg=315, altdeg=42)
    shaded = light.shade_rgb(
        biome_rgb.astype(np.float64) / 255.0,
        island.height,
        vert_exag=2.3,
        blend_mode="soft",
    )
    # Draw the analyzed route as a thin high-contrast overlay.
    preview = np.clip(shaded * 255.0, 0, 255).astype(np.uint8)
    canvas = Image.fromarray(preview, mode="RGB")
    draw = ImageDraw.Draw(canvas, mode="RGBA")
    half = island.config.world_size / 2.0
    object_colors = {
        "large": (45, 42, 41, 215),
        "medium": (72, 67, 64, 210),
        "small": (108, 100, 94, 205),
        "vegetation": (35, 84, 48, 225),
        "route_repair": (50, 190, 220, 235),
    }
    order = {"large": 0, "medium": 1, "small": 2, "vegetation": 3, "route_repair": 4}
    for item in sorted(island.objects, key=lambda value: order.get(str(value["category"]), 5)):
        x_value, _, z_value = item["position"]
        col = (float(x_value) + half) / island.config.world_size * (island.config.resolution - 1)
        row = (float(z_value) + half) / island.config.world_size * (island.config.resolution - 1)
        scale = max(float(component) for component in item["scale"])
        radius = max(1.0, scale / island.config.world_size * island.config.resolution * 0.52)
        color = object_colors.get(str(item["category"]), (255, 255, 255, 190))
        draw.ellipse((col - radius, row - radius, col + radius, row + radius), fill=color)

    for point in island.route:
        col = round((float(point["x"]) + half) / island.config.world_size * (island.config.resolution - 1))
        row = round((float(point["z"]) + half) / island.config.world_size * (island.config.resolution - 1))
        if 0 <= row < preview.shape[0] and 0 <= col < preview.shape[1]:
            color = (244, 72, 72, 255) if point["needs_hold"] else (255, 244, 166, 255)
            draw.ellipse((col - 1.5, row - 1.5, col + 1.5, row + 1.5), fill=color)
    canvas.save(path)


def _export_preview_3d(path: Path, island: BakedIsland, biome_rgb: np.ndarray) -> None:
    target = min(97, island.config.resolution)
    indices = np.linspace(0, island.config.resolution - 1, target).round().astype(int)
    height = island.height[np.ix_(indices, indices)] * island.config.world_height
    half = island.config.world_size / 2.0
    axis = np.linspace(-half, half, target)
    x, z = np.meshgrid(axis, axis)
    colors = biome_rgb[np.ix_(indices, indices)].astype(np.float64) / 255.0

    figure = Figure(figsize=(8, 6), dpi=120, facecolor=(0.91, 0.88, 0.80))
    FigureCanvasAgg(figure)
    axes = figure.add_subplot(111, projection="3d")
    axes.plot_surface(
        x,
        z,
        height,
        facecolors=colors,
        rstride=1,
        cstride=1,
        linewidth=0,
        antialiased=False,
        shade=True,
    )

    scatter_colors = {
        "large": "#342f2d",
        "medium": "#554e49",
        "small": "#857970",
        "vegetation": "#245c36",
        "route_repair": "#32bedc",
    }
    for category in ("large", "medium", "vegetation", "route_repair"):
        items = [item for item in island.objects if item["category"] == category]
        if not items:
            continue
        positions = np.asarray([item["position"] for item in items], dtype=float)
        sizes = np.asarray([max(item["scale"]) for item in items], dtype=float)
        axes.scatter(
            positions[:, 0],
            positions[:, 2],
            positions[:, 1] + sizes * 0.34,
            s=np.clip(sizes * 0.42, 3.0, 22.0),
            c=scatter_colors[category],
            depthshade=True,
            alpha=0.88,
        )
    if island.route:
        route = np.asarray(
            [[point["x"], point["z"], point["y"] + 5.0] for point in island.route],
            dtype=float,
        )
        axes.plot(route[:, 0], route[:, 1], route[:, 2], color="#fff0a8", linewidth=2.0)

    axes.set_box_aspect((1.0, 1.0, 1.65))
    axes.view_init(elev=31, azim=228)
    axes.set_xlim(-half, half)
    axes.set_ylim(-half, half)
    axes.set_zlim(0.0, island.config.world_height)
    axes.set_axis_off()
    figure.subplots_adjust(left=0, right=1, bottom=0, top=1)
    figure.savefig(path, facecolor=figure.get_facecolor(), bbox_inches="tight", pad_inches=0)


def export_bundle(output_dir: str | Path, island: BakedIsland) -> Path:
    output = Path(output_dir)
    output.mkdir(parents=True, exist_ok=True)

    height16 = np.round(island.height * 65535.0).astype(np.uint16)
    Image.fromarray(height16).save(output / "height.png")
    (output / "height.raw").write_bytes(height16.astype("<u2", copy=False).tobytes())

    biome_rgb = _biome_rgb(island)
    material_rgb = _material_rgb(island, biome_rgb)
    Image.fromarray(biome_rgb, mode="RGB").save(output / "biomes.png")
    Image.fromarray(material_rgb, mode="RGB").save(output / "materials.png")
    Image.fromarray(_normal_rgb(island), mode="RGB").save(output / "normal.png")
    Image.fromarray(
        np.round(island.occlusion * 255.0).astype(np.uint8), mode="L"
    ).save(output / "occlusion.png")

    _write_json(output / "config.json", island.config.to_dict())
    _write_json(output / "spawn_manifest.json", {"objects": island.objects})
    _write_json(output / "route.json", {"points": island.route})
    _write_json(output / "statistics.json", island.statistics)
    _export_obj(output / "terrain.obj", island)
    _export_preview(output / "preview.png", island, material_rgb)
    _export_preview_3d(output / "preview_3d.png", island, material_rgb)
    return output
